#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the HaBayit Next.js site.
# Runs after the repository is checked out. Safe to run repeatedly.
set -euo pipefail

cd "$(dirname "$0")/.."

npm ci

# Provide safe local defaults so `next dev`/`next build` boot without real
# secrets. Real values injected as Cloud Agent secrets (process.env) take
# precedence over these file values, and an existing .env.local is never
# overwritten, so developers can drop in real credentials at any time.
if [ ! -f .env.local ]; then
  cat > .env.local <<'EOF'
# Auto-generated by .cursor/install.sh for local Cloud Agent development.
# These are non-functional placeholders that let the app boot for UI work.
# To exercise database / payment / email features, provide the real values as
# Cloud Agent secrets (they override these) or edit this file directly.
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=https://placeholder.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key
STRIPE_SECRET_KEY=sk_test_placeholder
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_placeholder
EOF
  echo "[install] Wrote placeholder .env.local for local development."
else
  echo "[install] .env.local already present — leaving it untouched."
fi
