/** Generated by scripts/fetch-shabbat-fallback.mjs — do not edit manually. */
export const FALLBACK_SHABBAT_FETCHED_AT = "2026-09-09T07:01:33.538Z";

export const FALLBACK_SHABBAT = {
  "kind": "holiday",
  "kicker": "Rosh Hashana",
  "parsha": {
    "hebrew": "ראש השנה 5787",
    "englishName": "Rosh Hashana 5787"
  },
  "mevarchim": null,
  "fridayLabel": "Erev Rosh Hashana September 11th",
  "shabbatLabel": "Sunday September 13th",
  "candleLighting": "7:11pm",
  "shabbosEnds": "8:02pm",
  "secondCandleLabel": "Rosh Hashana 5787 September 12th",
  "secondCandleLighting": "8:03pm"
} as const;
