/** Generated by scripts/fetch-shabbat-fallback.mjs — do not edit manually. */
export const FALLBACK_SHABBAT_FETCHED_AT = "2026-07-20T02:50:17.844Z";

export const FALLBACK_SHABBAT = {
  "parsha": {
    "hebrew": "שבת פרשת ואתחנן",
    "englishName": "Vaetchanan"
  },
  "mevarchim": null,
  "fridayLabel": "Friday July 24th",
  "shabbatLabel": "Shabbat July 25th",
  "candleLighting": "7:53pm",
  "shabbosEnds": "8:49pm"
} as const;
