/** Generated by scripts/fetch-shabbat-fallback.mjs — do not edit manually. */
export const FALLBACK_SHABBAT_FETCHED_AT = "2026-09-09T06:58:30.975Z";

export const FALLBACK_SHABBAT = {
  "kind": "holiday",
  "kicker": "Rosh Hashana",
  "parsha": {
    "hebrew": "ראש השנה 5787",
    "englishName": "Rosh Hashana 5787"
  },
  "mevarchim": null,
  "fridayLabel": "Erev Rosh Hashana September 11th",
  "shabbatLabel": "Rosh Hashana II ends September 13th",
  "candleLighting": "7:11pm",
  "shabbosEnds": "8:02pm"
} as const;
